config/routes.rb
Animecult::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                            registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get 'adminka' => 'devise/sessions#new'
  end

  mount Commontator::Engine => '/commontator'

  root 'search#index'

  concern :searchable do
    collection do
      get :search
    end
  end

  resources :news
  resources :video, only: :show
  resources :genre, only: %i[index show]
  resources :category, only: %i[index show]
  resources :director, only: %i[index show]
  resources :author, only: %i[index show edit update]
  resources :studio, only: %i[index show]
  resources :translator, only: %i[index show]
  resources :anime_list, only: :index
  resources :tag, only: :show
  resources :attachments, only: :destroy
  resources :comment_tool, only: :index
  resources :by_year, only: %i[index show]
  resources :character, only: %i[new create show edit update], concerns: :searchable
  resources :song, only: %i[new create show edit update], concerns: :searchable
  resources :creator, only: %i[new create show edit update], concerns: :searchable
  resources :credit, only: [], concerns: :searchable
  resources :element, only: %i[edit update new create], concerns: :searchable
  resources :users, only: [], concerns: :searchable

  resources :user_social_networks, only: :destroy do
    collection do
      get ':provider/remove', action: :remove
    end
  end

  resources :moderate, only: :index do
    collection do
      get :revisions
      get :images
      get :objects
      post :appoint_editor
      post :appoint_moderator
      post :cancel_editor
      post :cancel_moderator
      post :do_action
      post :remove_attachment
      post :apply_attachment
      post :remove_attachment_ajax
      post :upload_attachments_ajax
    end
  end

  resources :account, only: :index do
    collection do
      post :change_nickname
      post :update_password
      post :notification_read
    end
  end

  resources :posts
  resources :translates
  resources :serial do
    collection do
      post :rate
    end

    member do
      get :translate
      get :characters
      get :creators
      get :songs
      post :toggle_hide_to_unregistered
    end

    resources :episode, only: %i[new create show edit update destroy] do
      member do
        post :create_chapter_link
        post :cancel_chapter_link
        post :create_chapter_video
        post :cancel_chapter_video
        post :toggle_hide_to_unregistered
      end
    end
  end

  resources :review do
    member do
      post :remove_image
    end
  end

  resources :image_elem, only: [] do
    member do
      post :remove_image
    end
  end

  resources :public, only: [] do
    collection do
      get :user_agreement
      get :copyright_holders
    end
  end

  resources :adblock, only: %i[index create destroy]
  resources :personal, only: :show do
    collection do
      get :ajax
    end
  end

  resources :admin, only: %i[index update] do
    collection do
      post :update_account_nickname
      post :update_seo_item
      get :account
    end
  end

  resources :test, only: :index do
    collection do
      post :ajax
      get :yookassa
    end
  end

  resources :favorite, only: :index do
    collection do
      post :toggle
    end
  end

  resources :revisions, only: :show do
    member do
      post :do_cancel
      post :do_apply
    end
  end

  resources :upload, only: [] do
    collection do
      post :upload_image
    end
  end

  resources 'not_found', only: :index

  get 'sitemap' => 'search#sitemap'
  get 'feeds', to: 'review#feed', format: 'rss'
  get '*path' => 'not_found#index'
end

app/controllers/serial_controller.rb
class SerialController < ApplicationController

  before_action :access_deny_if_not_a_user, only: [:rate, :edit, :update, :new, :create]
  before_action :set_serial, only: [:edit, :update, :translate, :toggle_hide_to_unregistered]
  before_action :access_deny_if_not_an_admin, only: [:toggle_hide_to_unregistered]

  def new
    @serial = Serial.new
  end

  def create
    @serial = Serial.new(serial_params)
    if @serial.save
      unless params[:attachments].blank?
        params[:attachments]['cover'].each do |cover|
          @serial.attachments.create!(cover: cover, main_object: @serial, is_applied: true, user: current_user)
        end
      end
      if current_user.only_could_revise?
        @serial.update_attribute(:is_applied, false)
      end
      @serial.update_attribute(:total_images,0)
      @serial.update_attribute( :user_id,current_user.id)
      redirect_to(serial_path(id:@serial.transliterated_link))
    else
      render 'new'
    end
  end

  def show
    @serial = Serial.includes(:reviews,
                              serial_elements: :element,
                              character_participates: [{character: :attachments}, {creator: :attachments}],
                              creator_participates: [:creator, :credit],song_participates: {song: {song_stuffs: [:creator,:credit]}})
                  .where(transliterated_link:params[:id])[0]
    @attachments = @serial.attachments.where(is_applied:true)
    @chapters = @serial.chapters.where(is_applied:true,is_cancelled:false).order('chapter_id desc')
    if @serial.blank?
      render('not_found/index',status:404) && return
    end
    @elements = Element.joins(:serial_elements).where("serial_id=#{@serial.id}").order(:elem_type,:title)
    @videos = Video.includes(:translator).where(serial_id:@serial.id,chapter_id:-1).order('video_date desc')
    @associated_serials = @serial.associated
    commontator_thread_show(@serial)
    Notification.where(correctable:@serial,user:current_user).update_all(shown:true) if user_signed_in?

    @seo_obj = @serial
  end

  def edit
  end

  def update
    allowed_elements = Element.select(:id).order(:id).map{|e|e.id}
    elements_params = params[:serial_elements].to_s.split(',').map(&:to_i).select{|id| allowed_elements.include?(id)}.uniq.sort

    songs_params = params[:serial_songs].to_s.split(',').map{|x| x.split('-').map(&:to_i)}.sort
    allowed_songs = Song.where(id:songs_params.map{|pair| pair[0]}).map(&:id)
    songs_params.select!{|pair| allowed_songs.include? pair[0]}

    characters_params = params[:serial_characters].to_s.split(',').map{|x| x.split('-').map(&:to_i)}.sort
    allowed_characters = Character.where(id:characters_params.map{|dataset| dataset[0]}).map(&:id)
    characters_params.select!{|dataset| allowed_characters.include? dataset[0]}
    allowed_creators = Creator.where(id:characters_params.map{|dataset| dataset[1]}).map(&:id)
    characters_params.select!{|dataset| allowed_creators.include? dataset[1]}

    creators_params = params[:serial_creators].to_s.split(',').map{|x| x.split('-').map(&:to_i)}.sort
    allowed_creators = Creator.where(id:creators_params.map{|dataset| dataset[0]}).map(&:id)
    creators_params.select!{|dataset| allowed_creators.include? dataset[0]}
    allowed_credits = Credit.where(id:creators_params.map{|dataset| dataset[1]}).map(&:id)
    creators_params.select!{|dataset| allowed_credits.include? dataset[1]}


    covers = params[:attachments].blank? ? [] : params[:attachments]['cover']
    update_result = @serial.process_save(current_user,serial_params.to_hash,elements_params,songs_params,characters_params,creators_params,covers)
    if update_result
      redirect_to(serial_path(@serial.clear_link),notice: update_result)
    else
      render action: 'edit'
    end
  end

  def toggle_hide_to_unregistered
    @serial.hide_to_unregistered = !@serial.hide_to_unregistered
    @serial.save
    redirect_to(serial_path(@serial.transliterated_link))
  end

  def translate

  end

  def rate
    @serial = Serial.find(params[:serial_id].to_i)
    current_user.rate @serial, params[:score].to_i
  end

  def characters
    @serial = Serial.includes(character_participates: [:character, :creator])
                  .where(transliterated_link:params[:id])[0]
    if @serial.blank?
      render('not_found/index',status:404) && return
    end
  end

  def creators
    @serial = Serial.includes(creator_participates: [:creator, :credit])
                  .where(transliterated_link:params[:id])[0]
    if @serial.blank?
      render('not_found/index',status:404) && return
    end
  end

  def songs
    @serial = Serial.includes(song_participates: {song: {song_stuffs: [:creator,:credit]}}).where(transliterated_link:params[:id])[0]
    if @serial.blank?
      render('not_found/index',status:404) && return
    end
    if @serial.song_participates.blank?
      redirect_to(serial_path(@serial.transliterated_link),notice:'OST не найден') && return
    end
  end

  private
  def set_serial
    @serial = Serial.includes(serial_elements: :element,
                              song_participates: {song: {song_stuffs: [:creator,:credit]}},
                              character_participates: [:character, :creator],
                              creator_participates: [:creator, :credit],
    ).find(params[:id])
  end

  def serial_params
    params[:serial][:transliterated_link] = filter_text_for_url(params[:serial][:transliterated_link].downcase)
    if params[:serial][:transliterated_link].blank?
      params[:serial][:transliterated_link] = transliterate params[:serial][:title]
    end
    params[:serial][:transliterated_link] = process_unique_field(Serial,:transliterated_link,params[:serial][:transliterated_link],params['_method']=='patch')
    params[:serial][:description] = cure_froala(params[:serial][:description])
    params.require(:serial).permit(:transliterated_link,:title, :english_title, :original_title, :aka, :description, :release, :full_length, :adult, attachments_attributes: [:id,:serial_id,:cover])
  end
end

app/views/serial/_form.html.haml
.text-right=f.submit 'Сохранить', class: 'btn btn-primary'

=render partial: 'fragments/html/errors', locals: {obj: @serial}
.form-group
  =f.label :transliterated_link, Serial::EDITABLE_FIELDS[:transliterated_link]
  =f.text_field :transliterated_link, class: 'form-control', placeholder: 'Оставьте пустым для генерации из названия'
.form-group
  =f.label :title, Serial::EDITABLE_FIELDS[:title]
  =f.text_field :title, class: 'form-control'
.form-group
  =f.label :english_title, Serial::EDITABLE_FIELDS[:english_title]
  =f.text_field :english_title, class: 'form-control'
.form-group
  =f.label :original_title, Serial::EDITABLE_FIELDS[:original_title]
  =f.text_field :original_title, class: 'form-control'
.form-group
  =f.label :aka, Serial::EDITABLE_FIELDS[:aka]
  =f.text_area :aka, class: 'form-control', placeholder: 'Разделитель "/"'
.form-group
  .row
    .col-6
      =f.label :release, Serial::EDITABLE_FIELDS[:release]
      =f.number_field :release, in: 0..2050, step:1
      =f.label :full_length, Serial::EDITABLE_FIELDS[:full_length]
      =f.check_box :full_length
      =f.label :adult, Serial::EDITABLE_FIELDS[:adult]
      =f.check_box :adult
    .col-6
      =render partial: 'fragments/haml/images_block', locals: {object: @serial,form:f}
.form-group
  =f.label :description, Serial::EDITABLE_FIELDS[:description]
  =f.text_area :description,id:'froalaEditor',size: '50x20', class: 'form-control'

app/views/serial/characters.html.haml
-content_for :title do
  =@serial.seo_title_characters
-content_for :description do
  ="Все персонажи аниме #{@serial.title}"
%main.page
  .container-fluid
    .panel.bg-light
      %h1
        Все персонажи аниме
        =link_to(@serial.title,serial_path(@serial.transliterated_link))
        -acps = @serial.character_participates_by_category
        -acps.keys.sort.each do |category|
          %h2="#{CharacterParticipate::CATEGORY_TITLES[category][:many]}:"
          -acps[category].each_slice(6).to_a.each do |dataset|
            .row
              -dataset.each do |cp|
                .col-6.col-md-3
                  -unless cp.character.link.blank?
                    %a{href:character_path(cp.character.link)}
                      =cp.character.title
                      -unless cp.character.attachments.blank?
                        %br
                        =image_tag(cp.character.attachments[0].cover_url,class:'character-icon')
                .col-6.col-md-3
                  -unless cp.creator.blank?
                    %a{href:creator_path(cp.creator.link)}
                      =cp.creator.title
                      -unless cp.creator.attachments.blank?
                        %br
                        =image_tag(cp.creator.attachments[0].cover_url,class:'character-icon')

app/views/serial/creators.html.haml
-content_for :title do
  =@serial.seo_title_creators
-content_for :description do
  ="Все создатели аниме #{@serial.title}"
%main.page
  .container-fluid
    .panel.bg-light
      %h1
        Все создатели аниме
        =link_to(@serial.title,serial_path(@serial.transliterated_link))
      .serial-info-rows
        -creators_by_group(@serial).each_pair do |title,data|
          .serial-info-row
            .serial-info-name-expanded="#{title}:"
            .serial-info-value
              -data.sort_by{|x| x[:title]}.each_with_index do |obj,index|
                ="#{link_to(obj[:title],obj[:link])}#{data.size==index+1 ? '' : ','}".html_safe

app/views/serial/edit.html.haml
%main.page
  .container-fluid
    .panel.bg-light

      %h1.heading
        Редактирование аниме
        =link_to(@serial.title,serial_path(@serial.transliterated_link))

      =form_for(@serial) do |f|
        =render 'form', f:f

        %h3.heading-3 Элементы произведения
        %input.form-control#serial_element_search{placeholder:'Вводите название элемента для поиска...'}
        .row.align-items-center
          .col.text-right
            %a.btn.btn-secondary{href:new_element_path,target: '_blank'} К созданию элемента
        -Element::TITLES.each_pair do |elem_type,title|
          %div{id:"serial_elements_#{elem_type}"}
            %strong="#{title}:"
            -@serial.elements_by_elem_type[elem_type].each do |element|
              %span.serial-element-block{'data-id':element.id}
                =element.title
                %a.remove-link{href:'#'}
                  %span.badge.badge-alert X
        %input.serial-hidden#serial_elements{name:'serial_elements',value:@serial.serial_elements.map(&:element_id).sort.join(',')}

        %br
        %h3.heading-3 Саундтрек
        .row
          .col-4
            %select.form-control#song_relation
              -SongParticipate::SONG_RELATIONS.each_pair do |song_relation,title|
                %option{value:song_relation,default: song_relation==1}=title
          .col-8
            %input.form-control#serial_song_search{placeholder:'Вводите название песни для поиска...'}
        .row.align-items-center
          .col.text-right
            %a.btn.btn-secondary{href:new_song_path,target: '_blank'} К созданию песни
        -SongParticipate::SONG_RELATIONS.each_pair do |relation_id,title|
          %div{id:"serial_songs_#{relation_id}"}
            %strong=title
            -@serial.songs_by_relation_type[relation_id].each do |song|
              %span.serial-song-block{'data-id':"#{song.id}-#{relation_id}"}
                ="#{song.title} (#{SongParticipate::SONG_RELATIONS[relation_id]})"
                %a.remove-link{href:'#'}
                  %span.badge.badge-alert X
        %input.serial-hidden#serial_songs{name: :serial_songs,value:@serial.song_participates.map{|sp| "#{sp.song_id}-#{sp.relation_id}"}.join(',')}

        %br
        %h3.heading-3 Персонажи
        .row
          .col-3
            %select.form-control#character_category
              -CharacterParticipate::CATEGORY_TITLES.each_pair do |character_category,titles|
                %option{value:character_category,default: character_category==1}=titles[:single]
          .col-3
            %input.form-control#serial_character_search{placeholder:'Укажите персонажа...'}
          .col-3
            %input.form-control#serial_character_creator_search{placeholder:'Укажите сэйю...'}
          .col-3
            %a.btn.btn-success#add_serial_character{href:'#'} Добавить
        .row.align-items-center
          .col.text-right
            %a.btn.btn-secondary{href:new_character_path,target: '_blank'} К созданию персонажа
        -CharacterParticipate::CATEGORY_TITLES.each_pair do |category,dataset|
          %div{id:"serial_characters_#{category}"}
            %strong=dataset[:single]
            -@serial.characters_by_category[category].each do |cp|
              %span.serial-character-block{'data-id':"#{cp[:character].blank? ? '' : cp[:character].id}-#{cp[:creator].blank? ? '' : cp[:creator].id}-#{category}"}
                ="#{cp[:character].blank? ? '' : cp[:character].title} (#{cp[:creator].blank? ? '' : cp[:creator].title})"
                %a.remove-link{href:'#'}
                  %span.badge.badge-alert X
        %input.serial-hidden#serial_characters{name: :serial_characters,value:@serial.character_participates.map{|cp| "#{cp.character_id}-#{cp.creator_id}-#{cp.category}"}.join(',')}

        %br
        %h3.heading-3 Создатели
        .row
          .col-4
            %input.form-control#serial_creator_search{placeholder:'Персона...'}
          .col-4
            %input.form-control#serial_credit_search{placeholder:'Профессия...'}
          .col-1
          .col-3
            %a.btn.btn-success#add_serial_creator{href:'#'} Добавить
        .row.align-items-center
          .col.text-right
            %a.btn.btn-secondary{href:new_creator_path,target: '_blank'} К созданию персонала
        #serial_creator_items
          -@serial.creator_participates.each do |cp|
            -unless cp.creator.blank?
              %span.serial-creator-block{'data-id':"#{cp.creator.id}-#{cp.credit.id}"}
                ="#{cp.creator.title} (#{cp.credit.title})"
                %a.remove-link{href:'#'}
                  %span.badge.badge-alert X
        %input.serial-hidden#serial_creators{name: :serial_creators,value:@serial.creator_participates.select{|cp| !cp.creator.blank?}.map{|cp| "#{cp.creator.id}-#{cp.credit.id}"}.join(',')}


        .row.align-items-center
          .col=link_to 'Назад',serial_path(@serial.clear_link), class: 'btn btn-secondary'
          .col.text-right=f.submit 'Сохранить', class: 'btn btn-primary'

app/views/serial/new.html.haml
%main.page
  .container-fluid
    .panel.bg-light

      %h1.heading='Создание аниме'
      =form_for @serial, url: serial_index_path, html: {multipart: true} do |f|
        =render 'form', f:f

app/views/serial/songs.html.haml
-content_for :title do
  =@serial.seo_title_songs
-content_for :description do
  ="Все песни и вся музыка аниме #{@serial.title}"
%main.page
  .container-fluid
    .panel.bg-light
      %h1
        Песни и Музыка аниме
        =link_to(@serial.title,serial_path(@serial.clear_link))
        .serial-info-rows
          -relation_title = ''
          -@serial.song_participates.sort_by{|sp| [sp.relation_id,sp.song.title]}.each_with_index do |sp,index|
            -unless relation_title==sp.relation_title
              %h2=sp.relation_title
              -relation_title = sp.relation_title
            .serial-info-row
              .serial-info-name-expanded
                %h3=link_to(sp.song.title,song_path(sp.song.link))
              .serial-info-value
                -sp.song.song_stuffs.each_with_index do |ss,index|
                  -unless index.zero?
                    ,
                  ="#{ss.credit.title_translated}:"
                  =link_to(ss.creator.title,creator_path(ss.creator.link))

app/views/serial/translate.html.haml
.row
  .large-12.columns2
    .panel
      %h1=t('.h1',{serial:@serial.title})
      -if flash[:notice]
        .alert-box{'data-alert'=>true}=flash[:notice]
      %p
        %b=t('.original')
        =@serial.description2
      %h3=t('.translates')
      %table
        %tbody
          -if user_signed_in?
            -@serial.translates.order(:description).each do |translate|
              %tr
                %td{style:'width:100%'}
                  -if translate.selected
                    %b=translate.description
                  -else
                    =translate.description
                %td{style:'width:100px;'}=link_to t('.show'),translate_path(translate)
                %td{style:'width:100px;'}=link_to t('.edit'),edit_translate_path(id:translate,serial_id:@serial.id)
          -else
            %tr
              %td{style:'width:100%'}
                %b=@serial.translate.description
              %td{style:'width:100px;'}=link_to t('.show'),translate_path(@serial.translate)
      %a{href:new_translate_path(serial_id:@serial.id)}
        .button.tiny=t('.add_translate')
      %a{href:serial_path(@serial.clear_link)}
        .button.tiny.right=t('.back')