config/routes.rb
Animecult::Application.routes.draw do
  devise_for :users,
             controllers: { omniauth_callbacks: 'omniauth_callbacks',
                            registrations: 'registrations', sessions: 'sessions' }
  devise_scope :user do
    get 'adminka' => 'devise/sessions#new'
  end

  mount Commontator::Engine => '/commontator'

  root 'search#index'

  concern :searchable do
    collection do
      get :search
    end
  end

  resources :news
  resources :video, only: :show
  resources :genre, only: %i[index show]
  resources :category, only: %i[index show]
  resources :director, only: %i[index show]
  resources :author, only: %i[index show edit update]
  resources :studio, only: %i[index show]
  resources :translator, only: %i[index show]
  resources :anime_list, only: :index
  resources :tag, only: :show
  resources :attachments, only: :destroy
  resources :comment_tool, only: :index
  resources :by_year, only: %i[index show]
  resources :character, only: %i[new create show edit update], concerns: :searchable
  resources :song, only: %i[new create show edit update], concerns: :searchable
  resources :creator, only: %i[new create show edit update], concerns: :searchable
  resources :credit, only: [], concerns: :searchable
  resources :element, only: %i[edit update new create], concerns: :searchable
  resources :users, only: [], concerns: :searchable

  resources :user_social_networks, only: :destroy do
    collection do
      get ':provider/remove', action: :remove
    end
  end

  resources :moderate, only: :index do
    collection do
      get :revisions
      get :images
      get :objects
      post :appoint_editor
      post :appoint_moderator
      post :cancel_editor
      post :cancel_moderator
      post :do_action
      post :remove_attachment
      post :apply_attachment
      post :remove_attachment_ajax
      post :upload_attachments_ajax
    end
  end

  resources :account, only: :index do
    collection do
      post :change_nickname
      post :update_password
      post :notification_read
    end
  end

  resources :posts
  resources :translates
  resources :serial do
    collection do
      post :rate
    end

    member do
      get :translate
      get :characters
      get :creators
      get :songs
      post :toggle_hide_to_unregistered
    end

    resources :episode, only: %i[new create show edit update destroy] do
      member do
        post :create_chapter_link
        post :cancel_chapter_link
        post :create_chapter_video
        post :cancel_chapter_video
        post :toggle_hide_to_unregistered
      end
    end
  end

  resources :review do
    member do
      post :remove_image
    end
  end

  resources :image_elem, only: [] do
    member do
      post :remove_image
    end
  end

  resources :public, only: [] do
    collection do
      get :user_agreement
      get :copyright_holders
    end
  end

  resources :adblock, only: %i[index create destroy]
  resources :personal, only: :show do
    collection do
      get :ajax
    end
  end

  resources :admin, only: %i[index update] do
    collection do
      post :update_account_nickname
      post :update_seo_item
      get :account
    end
  end

  resources :test, only: :index do
    collection do
      post :ajax
      get :yookassa
    end
  end

  resources :favorite, only: :index do
    collection do
      post :toggle
    end
  end

  resources :revisions, only: :show do
    member do
      post :do_cancel
      post :do_apply
    end
  end

  resources :upload, only: [] do
    collection do
      post :upload_image
    end
  end

  resources 'not_found', only: :index

  get 'sitemap' => 'search#sitemap'
  get 'feeds', to: 'review#feed', format: 'rss'
  get '*path' => 'not_found#index'
end

app/models/revision.rb
# frozen_string_literal: true

class Revision < ApplicationRecord
  CONTENT_TYPE_DEFAULT = 1
  CONTENT_TYPE_SERIAL_CHANGES = 1
  CONTENT_TYPE_SERIAL_ELEMENTS = 2
  CONTENT_TYPE_SERIAL_SONGS = 3
  CONTENT_TYPE_SERIAL_CHARACTERS = 4
  CONTENT_TYPE_SERIAL_CREATORS = 5
  CONTENT_TYPE_SONG_STUFFS = 2
  ALLOWED_ACTIONS = {
    do_apply: 'одобрение',
    undo_apply: 'отмена',
    do_cancel: 'блокировка',
    undo_cancel: 'разблокировка'
  }.freeze
  ALLOWED_TYPES = {
    serial: Serial,
    element: Element,
    chapter: Chapter,
    song: Song,
    character: Character,
    creator: Creator,
    review: Review,
    new: New,
    chapter_link: ChapterLink,
    video: Video
  }.freeze

  belongs_to :user
  belongs_to :correctable, polymorphic: true

  def title
    result = [user.present? ? "Правка от #{user.show_title}." : 'Автор правки не найден.']
    result <<
      if correctable.present?
        [correctable.class::NAME, correctable.title, '.'].reject(&:blank?).join(' ')
      else
        'Объект правки не найден.'
      end
    result
  end

  def do_apply
    return if correctable.nil?

    if correctable.is_a?(Serial)
      case content_type
      when Revision::CONTENT_TYPE_SERIAL_ELEMENTS
        SerialElement.where(serial_id: correctable_id, element_id: body['add'] + body['delete']).delete_all
        body['add'].each { |element_id| SerialElement.create(serial_id: correctable_id, element_id: element_id) }
        correctable.update_attribute(:elements_are_locked, true)
      when Revision::CONTENT_TYPE_SERIAL_SONGS
        correctable.song_participates.each do |sp|
          (body['add'] + body['delete']).each do |song_id, relation_id|
            sp.destroy if sp.song_id == song_id && sp.relation_id == relation_id
          end
        end
        body['add'].each do |song_id, relation_id|
          SongParticipate.create(serial_id: correctable_id, song_id: song_id, relation_id: relation_id)
        end
      when Revision::CONTENT_TYPE_SERIAL_CHARACTERS
        correctable.character_participates.each do |cp|
          (body['add'] + body['delete']).each do |character_id, creator_id, category|
            cp.destroy if cp.character_id == character_id && cp.creator_id == creator_id && cp.category == category
          end
        end
        body['add'].each do |character_id, creator_id, category|
          CharacterParticipate.create(serial_id: correctable_id, character_id: character_id,
                                      creator_id: creator_id, category: category)
        end
      when Revision::CONTENT_TYPE_SERIAL_CREATORS
        correctable.creator_participates.each do |cp|
          (body['add'] + body['delete']).each do |creator_id, credit_id|
            cp.destroy if cp.creator_id == creator_id && cp.credit_id == credit_id
          end
        end
        body['add'].each do |creator_id, credit_id|
          CreatorParticipate.create(serial_id: correctable_id, creator_id: creator_id, credit_id: credit_id)
        end
      else
        correctable.update_attribute(:is_locked, true)
      end
    elsif correctable.is_a?(Song) && content_type == Revision::CONTENT_TYPE_SONG_STUFFS
      correctable.song_stuffs.each do |ss|
        (body['add'] + body['delete']).each do |creator_id, credit_id|
          ss.destroy if ss.creator_id == creator_id && ss.credit_id == credit_id
        end
      end
      body['add'].each do |creator_id, credit_id|
        SongStuff.create(song_id: correctable_id, creator_id: creator_id, credit_id: credit_id)
      end
    else
      correctable.update(body)
    end
  end
end

# == Schema Information
#
# Table name: revisions
#
#  id               :bigint           not null, primary key
#  body             :json
#  content_type     :integer          default(1)
#  correctable_type :string
#  is_applied       :boolean          default(FALSE)
#  is_cancelled     :boolean          default(FALSE)
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  correctable_id   :integer
#  user_id          :bigint
#
# Indexes
#
#  index_revisions_on_correctable_type_and_correctable_id  (correctable_type,correctable_id)
#  index_revisions_on_user_id                              (user_id)
#

app/controllers/revisions_controller.rb
class RevisionsController < ApplicationController
  before_action :access_deny_if_could_not_moderate

  def show
    @revision = Revision.includes(:user,:correctable).find(params[:id])
    if @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_ELEMENTS
      elements = {}
      serial_elements_to_add = @revision.body['add']
      serial_elements_to_delete = @revision.body['delete']
      Element::TITLES.each_pair do |id,title|
        elements[id] = {title: title, values: []}
      end
      Element.all.each do |e|
        elements[e.elem_type][:values] << {elem: e, action: :add} if serial_elements_to_add.include?(e.id)
        elements[e.elem_type][:values] << {elem: e, action: :remove} if serial_elements_to_delete.include?(e.id)
      end
      @elements = elements

    elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_SONGS
      songs = {}
      songs_to_add = @revision.body['add']
      songs_to_delete = @revision.body['delete']
      SongParticipate::SONG_RELATIONS.each_pair do |id,title|
        songs[id] = {title: title, values: []}
      end
      allowed_songs = {}
      Song.where(id: (songs_to_add + songs_to_delete).map{|pair| pair[0]}).each do |song|
        allowed_songs[song.id] = song
      end
      (songs_to_add + songs_to_delete).each do |pair|
        action = songs_to_add.include?(pair) ? :add : :remove
        song_id,relation_id = pair
        songs[relation_id][:values] << {song:allowed_songs[song_id], action: action} if allowed_songs.include?(song_id)
      end
      @songs = songs

    elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_CHARACTERS
      characters = {}
      characters_to_add = @revision.body['add']
      characters_to_delete = @revision.body['delete']
      CharacterParticipate::CATEGORY_TITLES.each_pair do |category,dataset|
        characters[category] = {title: dataset[:single], values: []}
      end
      allowed_characters = {}
      Character.where(id: (characters_to_add + characters_to_delete).map{|pair| pair[0]}).each do |character|
        allowed_characters[character.id] = character
      end
      allowed_creators = {}
      Creator.where(id: (characters_to_add + characters_to_delete).map{|pair| pair[1]}).each do |creator|
        allowed_creators[creator.id] = creator
      end
      (characters_to_add + characters_to_delete).each do |character_id,creator_id,category|
        action = characters_to_add.include?([character_id,creator_id,category]) ? :add : :remove
        if allowed_creators.include?(creator_id) && allowed_characters.include?(character_id)
          characters[category][:values] << {character: allowed_characters[character_id],creator: allowed_creators[creator_id], action: action}
        end
      end
      @characters = characters

    elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_CREATORS
      creators = []
      creators_to_add = @revision.body['add']
      creators_to_delete = @revision.body['delete']
      allowed_creators = {}
      Creator.where(id: (creators_to_add + creators_to_delete).map{|pair| pair[0]}).each do |creator|
        allowed_creators[creator.id] = creator
      end
      allowed_credits = {}
      Credit.where(id: (creators_to_add + creators_to_delete).map{|pair| pair[1]}).each do |credit|
        allowed_credits[credit.id] = credit
      end
      (creators_to_add + creators_to_delete).each do |creator_id,credit_id|
        action = creators_to_add.include?([creator_id,credit_id]) ? :add : :remove
        if allowed_creators.include?(creator_id) && allowed_credits.include?(credit_id)
          creators << {creator: allowed_creators[creator_id], credit: allowed_credits[credit_id], action: action}
        end
      end
      @creators = creators

    elsif @revision.correctable.is_a?(Song) && @revision.content_type==Revision::CONTENT_TYPE_SONG_STUFFS
      stuff = []
      stuff_to_add = @revision.body['add']
      stuff_to_delete = @revision.body['delete']
      allowed_creators = {}
      Creator.where(id: (stuff_to_add + stuff_to_delete).map{|pair| pair[0]}).each do |creator|
        allowed_creators[creator.id] = creator
      end
      allowed_credits = {}
      Credit.where(id: (stuff_to_add + stuff_to_delete).map{|pair| pair[1]}).each do |credit|
        allowed_credits[credit.id] = credit
      end
      (stuff_to_add + stuff_to_delete).each do |creator_id,credit_id|
        action = stuff_to_add.include?([creator_id,credit_id]) ? :add : :remove
        if allowed_creators.include?(creator_id) && allowed_credits.include?(credit_id)
          stuff << {creator: allowed_creators[creator_id], credit: allowed_credits[credit_id], action: action}
        end
      end
      @stuff = stuff
    end
  end

  def do_cancel
    @revision = Revision.find(params[:id])
    @revision.is_cancelled = true
    @revision.save
    Notification.create(correctable:@revision.correctable,user:@revision.user,title:Notification::TITLE_CHANGES_CANCELLED)
    redirect_to revisions_moderate_index_path
  end

  def do_apply
    @revision = Revision.find(params[:id])
    @revision.do_apply
    @revision.is_applied = true
    @revision.save
    Notification.create(correctable:@revision.correctable,user:@revision.user,title:Notification::TITLE_CHANGES_APPROVED)
    redirect_to revisions_moderate_index_path
  end

end

app/helpers/revisions_helper.rb
module RevisionsHelper

  def show_revision_value(value,field=nil)
    if field.nil?
      value
    elsif [false,true].include?(field)
      [true,'1'].include?(value) ? 'Да' : 'Нет'
    else value
    end
  end

end

app/views/revisions/show.html.haml
-content_for :title do
  Модерация правки
%main.page
  .container-fluid
    .panel.bg-light
      %h1.heading
        =@revision.title
        -if @revision.correctable.is_a?(Serial)
          =link_to("##{@revision.correctable.id}",serial_path(@revision.correctable.transliterated_link))
        -elsif @revision.correctable.is_a?(Chapter) && @revision.correctable.serial.is_a?(Serial)
          =link_to("##{@revision.correctable.id}",serial_episode_path(@revision.correctable.serial.transliterated_link,@revision.correctable.chapter_id))
      -if @revision.is_applied
        %span.badge.badge-success Принята
      -elsif !@revision.is_cancelled
        =link_to('Принять',do_apply_revision_path(@revision),method: :post,class:'btn btn-primary', :data => { :confirm => 'Вы уверены?'})
      -if @revision.is_cancelled
        %span.badge.badge-error Блокирована
      -else
        =link_to('Блокировать',do_cancel_revision_path(@revision),method: :post,class:'btn btn-danger', :data => { :confirm => 'Вы уверены?'})
      %table.table
        -if @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_ELEMENTS
          %h3.heading-3 Изменения элементов произведения
          %thead
            %tr
              %th Тип
              %th Изменения
          %tbody
            -@elements.each_pair do |elem_type,dataset|
              %tr
                %th=dataset[:title]
                %td
                  -dataset[:values].sort_by{|value| value[:action]==:add ? 1 : 0}.each do |value|
                    %span.badge{class:value[:action]==:add ? 'badge-primary' : 'badge-alert'}=value[:elem].title
        -elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_SONGS
          %h3.heading-3 Изменения песен произведения
          %thead
            %tr
              %th Тип
              %th Изменения
          %tbody
            -@songs.each_pair do |relation_id,dataset|
              %tr
                %th=dataset[:title]
                %td
                  -dataset[:values].sort_by{|value| value[:action]==:add ? 1 : 0}.each do |value|
                    %span.badge{class:value[:action]==:add ? 'badge-primary' : 'badge-alert'}=value[:song].title
        -elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_CHARACTERS
          %h3.heading-3 Изменения персонажей произведения
          %thead
            %tr
              %th Тип
              %th Изменения
          %tbody
            -@characters.each_pair do |category,dataset|
              %tr
                %th=dataset[:title]
                %td
                  -dataset[:values].sort_by{|value| value[:action]==:add ? 1 : 0}.each do |value|
                    %span.badge{class:value[:action]==:add ? 'badge-primary' : 'badge-alert'}
                      ="#{value[:character].title} (#{value[:creator].title})"
        -elsif @revision.correctable.is_a?(Serial) && @revision.content_type==Revision::CONTENT_TYPE_SERIAL_CREATORS
          %h3.heading-3 Изменения персонала произведения
          %thead
            %tr
              %th Изменения
          %tbody
            -@creators.each do |item|
              %tr
                %td
                  %span.badge{class:item[:action]==:add ? 'badge-primary' : 'badge-alert'}
                    ="#{item[:creator].title} (#{item[:credit].title})"
        -elsif @revision.correctable.is_a?(Song) && @revision.content_type==Revision::CONTENT_TYPE_SONG_STUFFS
          %h3.heading-3 Изменения персонала песни
          %thead
            %tr
              %th Изменения
          %tbody
            -@stuff.each do |item|
              %tr
                %td
                  %span.badge{class:item[:action]==:add ? 'badge-primary' : 'badge-alert'}
                    ="#{item[:creator].title} (#{item[:credit].title})"
        -else
          %thead
            %tr
              %th Поле
              %th Сейчас
              %th Изменение
          %tbody
            -@revision.body.each do |field,value|
              %tr
                %td=@revision.correctable.class::EDITABLE_FIELDS[field.to_sym]
                %td=show_revision_value(@revision.correctable.send(field),@revision.correctable.send(field))
                %td
                  -if @revision.content_type==Revision::CONTENT_TYPE_DEFAULT
                    =show_revision_value(value,@revision.correctable.send(field))